In [49]:
import pandas as pd
import requests 
from bs4 import BeautifulSoup

In [ ]:
headers={'User-Agent':'Mozilla/5.0 (Windows NT 6.3; Win 64 ; x64) Apple WeKit /537.36(KHTML , like Gecko) Chrome/80.0.3987.162 Safari/537.36'} 
webpage = requests.get('https://www.ambitionbox.com/list-of-companies?sortBy=popular&page=2',headers=headers).text

In [6]:
soup = BeautifulSoup(webpage,'lxml')

In [13]:
soup.find_all('h1')[0].text

'Aerospace & Defence companies'

In [25]:
company = soup.find_all('tr')

In [47]:
company

[<tr>
 <th class="text" scope="colgroup">
 <a aria-label="Default Sort" class="" href="?order=asc">S.No.</a>
 </th>
 <th class="text" scope="colgroup">
 <a aria-label="Sort on Name" class="" href="?sort=name&amp;order=desc">Name</a>
 </th>
 <th data-tooltip="Current Price" scope="colgroup">
 <a aria-label="Sort on Current Price" class="" href="?sort=current+price&amp;order=desc">
                     CMP
                     <span style="color: hsl(0, 0%, 45%)">Rs.</span>
 </a>
 </th>
 <th data-tooltip="Price to Earning" scope="colgroup">
 <a aria-label="Sort on Price to Earning" class="" href="?sort=price+to+earning&amp;order=desc">
                     P/E
                     <span style="color: hsl(0, 0%, 45%)"></span>
 </a>
 </th>
 <th data-tooltip="Market Capitalization" scope="colgroup">
 <a aria-label="Sort on Market Capitalization" class="desc" href="?sort=market+capitalization&amp;order=desc">
                     Mar Cap
                     <span style="color: hsl(0, 0%, 45%)">Rs.Cr.</span>
 </a>
 </th>
 <th data-tooltip="Dividend yield" scope="colgroup">
 <a aria-label="Sort on Dividend yield" class="" href="?sort=dividend+yield&amp;order=desc">
                     Div Yld
                     <span style="color: hsl(0, 0%, 45%)">%</span>
 </a>
 </th>
 <th data-tooltip="Net Profit latest quarter" scope="colgroup">
 <a aria-label="Sort on Net Profit latest quarter" class="" href="?sort=net+profit+latest+quarter&amp;order=desc">
                     NP Qtr
                     <span style="color: hsl(0, 0%, 45%)">Rs.Cr.</span>
 </a>
 </th>
 <th data-tooltip="YOY Quarterly profit growth" scope="colgroup">
 <a aria-label="Sort on YOY Quarterly profit growth" class="" href="?sort=yoy+quarterly+profit+growth&amp;order=desc">
                     Qtr Profit Var
                     <span style="color: hsl(0, 0%, 45%)">%</span>
 </a>
 </th>
 <th data-tooltip="Sales latest quarter" scope="colgroup">
 <a aria-label="Sort on Sales latest quarter" class="" href="?sort=sales+latest+quarter&amp;order=desc">
                     Sales Qtr
                     <span style="color: hsl(0, 0%, 45%)">Rs.Cr.</span>
 </a>
 </th>
 <th data-tooltip="YOY Quarterly sales growth" scope="colgroup">
 <a aria-label="Sort on YOY Quarterly sales growth" class="" href="?sort=yoy+quarterly+sales+growth&amp;order=desc">
                     Qtr Sales Var
                     <span style="color: hsl(0, 0%, 45%)">%</span>
 </a>
 </th>
 <th data-tooltip="Return on capital employed" scope="colgroup">
 <a aria-label="Sort on Return on capital employed" class="" href="?sort=return+on+capital+employed&amp;order=desc">
                     ROCE
                     <span style="color: hsl(0, 0%, 45%)">%</span>
 </a>
 </th>
 </tr>,
 <tr data-row-company-id="1274307">
 <td class="text">1.</td>
 <td class="text">
 <a href="/company/HAL/" target="_blank">Hind.Aeronautics</a>
 </td>
 <td>3311.15</td><td>25.61</td><td>221444.91</td><td>1.06</td><td>1432.60</td><td>14.29</td><td>6956.93</td><td>14.78</td><td>38.88</td>
 </tr>,
 <tr data-row-company-id="456">
 <td class="text">2.</td>
 <td class="text">
 <a href="/company/BEL/consolidated/" target="_blank">Bharat Electron</a>
 </td>
 <td>264.71</td><td>38.77</td><td>193489.64</td><td>0.83</td><td>1311.60</td><td>52.51</td><td>5770.69</td><td>38.65</td><td>34.61</td>
 </tr>,
 <tr data-row-company-id="1274794">
 <td class="text">3.</td>
 <td class="text">
 <a href="/company/MAZDOCK/consolidated/" target="_blank">Mazagon Dock</a>
 </td>
 <td>2162.50</td><td>31.71</td><td>87234.97</td><td>0.63</td><td>807.04</td><td>28.76</td><td>3143.62</td><td>33.06</td><td>44.19</td>
 </tr>,
 <tr data-row-company-id="3115">
 <td class="text">4.</td>
 <td class="text">
 <a href="/company/SOLARINDS/consolidated/" target="_blank">Solar Industries</a>
 </td>
 <td>9038.40</td><td>72.92</td><td>81838.67</td><td>0.09</td><td>337.50</td><td>54.86</td><td>1973.08</td><td>38.06</td><td>32.47</td>
 </tr>,
 <tr data-row-company-id="1274300">
 <td class="text">5.</td>
 <td class="text">
 <a href="/company/BDL/" target="_blank">Bharat Dynamics</a>
 </td>
 <td>1049.30</td><td>67.96</td><td>38443.78</td><td>0.50</td><td>147.13</td><td>8.96</td><td>832.14</td><td>38.32</td><td>24.23</td>
 </tr>,
 <tr data-row-company-id="1274120">
 <td class="text">6.</td>
 <td class="text">
 <a href="/company/COCHINSHIP/" target="_blank">Cochin Shipyard</a>
 </td>
 <td>1261.85</td><td>40.35</td><td>33202.30</td><td>0.77</td><td>184.29</td><td>-25.70</td><td>1069.88</td><td>4.74</td><td>21.62</td>
 </tr>,
 <tr data-row-company-id="1554">
 <td class="text">7.</td>
 <td class="text">
 <a href="/company/ITI/" target="_blank">ITI</a>
 </td>
 <td>246.33</td><td></td><td>23744.28</td><td>0.00</td><td>-67.12</td><td>34.00</td><td>1034.54</td><td>299.68</td><td>-8.43</td>
 </tr>,
 <tr data-row-company-id="1274573">
 <td class="text">8.</td>
 <td class="text">
 <a href="/company/GRSE/" target="_blank">Garden Reach Sh.</a>
 </td>
 <td>1263.80</td><td>36.71</td><td>14493.19</td><td>0.74</td><td>98.19</td><td>11.26</td><td>1271.01</td><td>37.69</td><td>27.37</td>
 </tr>,
 <tr data-row-company-id="423">
 <td class="text">9.</td>
 <td class="text">
 <a href="/company/BEML/consolidated/" target="_blank">BEML Ltd</a>
 </td>
 <td>2491.45</td><td>39.59</td><td>10363.72</td><td>0.82</td><td>24.41</td><td>-49.36</td><td>875.77</td><td>-16.35</td><td>15.25</td>
 </tr>,
 <tr data-row-company-id="3791">
 <td class="text">10.</td>
 <td class="text">
 <a href="/company/ZENTEC/consolidated/" target="_blank">Zen Technologies</a>
 </td>
 <td>1076.40</td><td>45.79</td><td>9730.53</td><td>0.09</td><td>42.67</td><td>33.07</td><td>152.21</td><td>52.94</td><td>45.97</td>
 </tr>,
 <tr data-row-company-id="1275127">
 <td class="text">11.</td>
 <td class="text">
 <a href="/company/DATAPATTNS/" target="_blank">Data Pattern</a>
 </td>
 <td>1411.60</td><td>44.20</td><td>7904.90</td><td>0.46</td><td>44.66</td><td>-12.38</td><td>117.04</td><td>-16.11</td><td>19.71</td>
 </tr>,
 <tr data-row-company-id="308">
 <td class="text">12.</td>
 <td class="text">
 <a href="/company/ASTRAMICRO/consolidated/" target="_blank">Astra Microwave</a>
 </td>
 <td>611.80</td><td>43.16</td><td>5801.09</td><td>0.33</td><td>47.43</td><td>9.34</td><td>258.54</td><td>11.91</td><td>18.77</td>
 </tr>,
 <tr data-row-company-id="1285207">
 <td class="text">13.</td>
 <td class="text">
 <a href="/company/UNIMECH/consolidated/" target="_blank">Unimech Aero.</a>
 </td>
 <td>918.65</td><td>80.74</td><td>4686.69</td><td>0.00</td><td>15.57</td><td>-23.60</td><td>53.90</td><td>-16.72</td><td>75.43</td>
 </tr>,
 <tr data-row-company-id="1274316">
 <td class="text">14.</td>
 <td class="text">
 <a href="/company/MIDHANI/" target="_blank">Mishra Dhatu Nig</a>
 </td>
 <td>244.69</td><td>45.72</td><td>4586.58</td><td>0.58</td><td>25.27</td><td>102.32</td><td>237.96</td><td>-5.56</td><td>9.44</td>
 </tr>,
 <tr data-row-company-id="1274841">
 <td class="text">15.</td>
 <td class="text">
 <a href="/company/MTARTECH/" target="_blank">MTAR Technologie</a>
 </td>
 <td>1277.90</td><td>87.87</td><td>3929.53</td><td>0.00</td><td>16.33</td><td>54.64</td><td>174.45</td><td>47.56</td><td>11.38</td>
 </tr>,
 <tr>
 <th class="text" scope="colgroup">
 <a aria-label="Default Sort" class="" href="?order=asc">S.No.</a>
 </th>
 <th class="text" scope="colgroup">
 <a aria-label="Sort on Name" class="" href="?sort=name&amp;order=desc">Name</a>
 </th>
 <th data-tooltip="Current Price" scope="colgroup">
 <a aria-label="Sort on Current Price" class="" href="?sort=current+price&amp;order=desc">
                     CMP
                     <span style="color: hsl(0, 0%, 45%)">Rs.</span>
 </a>
 </th>
 <th data-tooltip="Price to Earning" scope="colgroup">
 <a aria-label="Sort on Price to Earning" class="" href="?sort=price+to+earning&amp;order=desc">
                     P/E
                     <span style="color: hsl(0, 0%, 45%)"></span>
 </a>
 </th>
 <th data-tooltip="Market Capitalization" scope="colgroup">
 <a aria-label="Sort on Market Capitalization" class="desc" href="?sort=market+capitalization&amp;order=desc">
                     Mar Cap
                     <span style="color: hsl(0, 0%, 45%)">Rs.Cr.</span>
 </a>
 </th>
 <th data-tooltip="Dividend yield" scope="colgroup">
 <a aria-label="Sort on Dividend yield" class="" href="?sort=dividend+yield&amp;order=desc">
                     Div Yld
                     <span style="color: hsl(0, 0%, 45%)">%</span>
 </a>
 </th>
 <th data-tooltip="Net Profit latest quarter" scope="colgroup">
 <a aria-label="Sort on Net Profit latest quarter" class="" href="?sort=net+profit+latest+quarter&amp;order=desc">
                     NP Qtr
                     <span style="color: hsl(0, 0%, 45%)">Rs.Cr.</span>
 </a>
 </th>
 <th data-tooltip="YOY Quarterly profit growth" scope="colgroup">
 <a aria-label="Sort on YOY Quarterly profit growth" class="" href="?sort=yoy+quarterly+profit+growth&amp;order=desc">
                     Qtr Profit Var
                     <span style="color: hsl(0, 0%, 45%)">%</span>
 </a>
 </th>
 <th data-tooltip="Sales latest quarter" scope="colgroup">
 <a aria-label="Sort on Sales latest quarter" class="" href="?sort=sales+latest+quarter&amp;order=desc">
                     Sales Qtr
                     <span style="color: hsl(0, 0%, 45%)">Rs.Cr.</span>
 </a>
 </th>
 <th data-tooltip="YOY Quarterly sales growth" scope="colgroup">
 <a aria-label="Sort on YOY Quarterly sales growth" class="" href="?sort=yoy+quarterly+sales+growth&amp;order=desc">
                     Qtr Sales Var
                     <span style="color: hsl(0, 0%, 45%)">%</span>
 </a>
 </th>
 <th data-tooltip="Return on capital employed" scope="colgroup">
 <a aria-label="Sort on Return on capital employed" class="" href="?sort=return+on+capital+employed&amp;order=desc">
                     ROCE
                     <span style="color: hsl(0, 0%, 45%)">%</span>
 </a>
 </th>
 </tr>,
 <tr data-row-company-id="1274969">
 <td class="text">16.</td>
 <td class="text">
 <a href="/company/PARAS/consolidated/" target="_blank">Paras Defence</a>
 </td>
 <td>870.45</td><td>69.79</td><td>3507.78</td><td>0.00</td><td>13.85</td><td>136.35</td><td>85.77</td><td>33.64</td><td>10.32</td>
 </tr>,
 <tr data-row-company-id="1274254">
 <td class="text">17.</td>
 <td class="text">
 <a href="/company/APOLLO/" target="_blank">Apollo Micro Sys</a>
 </td>
 <td>111.74</td><td>61.08</td><td>3423.78</td><td>0.04</td><td>18.44</td><td>82.39</td><td>148.39</td><td>62.46</td><td>12.01</td>
 </tr>,
 <tr data-row-company-id="340">
 <td class="text">18.</td>
 <td class="text">
 <a href="/company/AVANTEL/" target="_blank">Avantel</a>
 </td>
 <td>109.74</td><td>40.92</td><td>2685.87</td><td>0.18</td><td>20.90</td><td>23.16</td><td>70.44</td><td>19.19</td><td>47.50</td>
 </tr>,
 <tr data-row-company-id="1275347">
 <td class="text">19.</td>
 <td class="text">
 <a href="/company/DCXINDIA/" target="_blank">DCX Systems</a>
 </td>
 <td>234.12</td><td>49.90</td><td>2610.09</td><td>0.00</td><td>11.65</td><td>-2.02</td><td>283.11</td><td>43.00</td><td>9.27</td>
 </tr>,
 <tr data-row-company-id="1284396">
 <td class="text">20.</td>
 <td class="text">
 <a href="/company/IDEAFORGE/consolidated/" target="_blank">Ideaforge Tech</a>
 </td>
 <td>341.60</td><td></td><td>1474.70</td><td>0.00</td><td>-24.02</td><td>-262.30</td><td>17.61</td><td>-80.63</td><td>11.49</td>
 </tr>,
 <tr data-row-company-id="1599">
 <td class="text">21.</td>
 <td class="text">
 <a href="/company/500306/consolidated/" target="_blank">Jaykay Enter.</a>
 </td>
 <td>116.45</td><td>90.10</td><td>1361.48</td><td>0.00</td><td>5.39</td><td>894.23</td><td>21.73</td><td>188.20</td><td>3.97</td>
 </tr>,
 <tr data-row-company-id="327304">
 <td class="text">22.</td>
 <td class="text">
 <a href="/company/NIBE/consolidated/" target="_blank">NIBE</a>
 </td>
 <td>901.45</td><td>44.04</td><td>1283.35</td><td>0.11</td><td>1.94</td><td>-55.71</td><td>148.68</td><td>137.17</td><td>15.81</td>
 </tr>,
 <tr data-row-company-id="3064">
 <td class="text">23.</td>
 <td class="text">
 <a href="/company/523606/consolidated/" target="_blank">Sika Interplant</a>
 </td>
 <td>2411.10</td><td>41.49</td><td>1022.31</td><td>0.41</td><td>7.14</td><td>50.95</td><td>37.98</td><td>46.08</td><td>25.58</td>
 </tr>,
 <tr data-row-company-id="1285189">
 <td class="text">24.</td>
 <td class="text">
 <a href="/company/ROSSTECH/consolidated/" target="_blank">Rossell Techsys</a>
 </td>
 <td>266.05</td><td>90.15</td><td>1010.57</td><td>0.00</td><td>5.20</td><td>163.96</td><td>75.74</td><td>30.56</td><td></td>
 </tr>,
 <tr data-row-company-id="1284371">
 <td class="text">25.</td>
 <td class="text">
 <a href="/company/543920/" target="_blank">CFF Fluid</a>
 </td>
 <td>399.65</td><td>36.99</td><td>778.29</td><td>0.25</td><td>14.05</td><td></td><td>80.03</td><td>34.62</td><td>24.02</td>
 </tr>]

In [46]:
name = []

for i in company:
    name.append(i.find('td',class_="text").strip())

AttributeError: 'NoneType' object has no attribute 'strip'

SyntaxError: invalid syntax (4005615637.py, line 4)